name: Front CI/CD

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

#     Docker Node Image 사용으로 Node 세팅에 필요한 시간 단축 (Node 18.17 ver)
#      - name: Use Node.js 18.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: 18.x

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Stop old server (ignore error)
        run: |
          killall -9 node || true

      - name: Remove old server in ~/soruce (ignore error)
        run: |
          rm -rf ~/source || true

      - name: Copy new server to ~/soruce
        run: |
          mkdir -p ~/source
          cp -R ./ ~/source

      - name: Run new server (in background)
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          cd ~/source
          nohup npm run dev </dev/null >/dev/null 2>&1 &